$(document).ready(function(){
	// 탭 메뉴 show/hide 목록
	$(".contentLeft").hide();		
	$("#mypage-content-left-counter").show();
	$("#mypage-content-left-tracks").show();
	
	$(".mypage-menubarOuter-menubarInner-tracks").click(function(){
		$(".contentLeft").hide();
		$("#mypage-content-left-counter").show();
		$("#mypage-content-left-tracks").show();
	});
	$(".mypage-menubarOuter-menubarInner-playlists").click(function(){
		$(".contentLeft").hide();
		$("#mypage-content-left-counter").show();
		$("#mypage-content-left-playlists").show();			
	});
	$(".mypage-menubarOuter-menubarInner-socials").click(function(){
		$(".contentLeft").hide();
		$(".contentLeft-socials").hide();
		$("#mypage-content-left-socialsButtons").show();			
		$("#mypage-content-left-socials").show();
		$("#mypage-content-left-socials-following").show();
	});
	// 탭메뉴 socials의 서브 메뉴 출력
	$(".btn-socials-following").click(function(){
		$(".contentLeft-socials").hide();
		$("#mypage-content-left-socialsButtons").show();
		$("#mypage-content-left-socials-following").show();
	});
	$(".btn-socials-followers").click(function(){
		$(".contentLeft-socials").hide();
		$("#mypage-content-left-socialsButtons").show();
		$("#mypage-content-left-socials-followers").show();
	});
	$(".btn-socials-likes").click(function(){
		$(".contentLeft-socials").hide();
		$("#mypage-content-left-socialsButtons").show();
		$("#mypage-content-left-socials-likes").show();
	});
	$(".btn-socials-comments").click(function(){
		$(".contentLeft-socials").hide();
		$("#mypage-content-left-socialsButtons").show();
		$("#mypage-content-left-socials-comments").show();
	});
});