DROP TABLE ALBUM_IMG;
CREATE TABLE ALBUM_IMG
(
ALBUM_IMG_NUM NUMBER(10) PRIMARY KEY,
ORG_FILE_NAME VARCHAR2(600),
SAVED_FILE_NAME VARCHAR2(600),
FILE_SIZE NUMBER(10)
);

DROP SEQUENCE ALBUM_IMG_SEQ;
CREATE SEQUENCE ALBUM_IMG_SEQ;