DROP TABLE ALBUM_LIKE;
CREATE TABLE ALBUM_LIKE
(
ALBUM_LIKE_NUM NUMBER(10) PRIMARY KEY,
MEMBER_ID VARCHAR2(30), --FK MEMBER
ALBUM_INFO_NUM NUMBER(10) --FK ALBUM-ALBUM_NUM
);

DROP SEQUENCE ALBUM_LIKE_SEQ;
CREATE SEQUENCE ALBUM_LIKE_SEQ;