DROP TABLE ALBUM_TAG;
CREATE TABLE ALBUM_TAG
(
ALBUM_TAG_NUM NUMBER(10) PRIMARY KEY,
ALBUM_TAG_NAME VARCHAR2(50),
ALBUM_INFO_NUM NUMBER(10)    --FK FOR ALBUM_INFO
);

DROP SEQUENCE ALBUM_TAG_SEQ;
CREATE SEQUENCE ALBUM_TAG_SEQ;