DROP TABLE ALBUM_INFO;
CREATE TABLE ALBUM_INFO
(
ALBUM_INFO_NUM NUMBER(10),
ALBUM_TITLE VARCHAR2(60),
ALBUM_PUBLISHER VARCHAR2(30), --MEMBER테이블을 위한FK
ARTIST VARCHAR2(30),
GENRE_CODE NUMBER(10),  --GENRE테이블을 위한FK
ALBUM_RELEASE_DATE DATE,
ALBUM_PUBLIC NUMBER(1),
ALBUM_IMG_NUM NUMBER(10), --앨범이미지테이블을 위한 FK
ALBUM_TYPE_CODE NUMBER(10), --앨범타입테이블을 위한 FK
ALBUM_LIKECOUNT NUMBER(10)
);

DROP SEQUENCE ALBUM_INFO_SEQ;
CREATE SEQUENCE ALBUM_INFO_SEQ;
