DROP TABLE COMMENTS;
CREATE TABLE COMMENTS
(
COMMENTS_NUM NUMBER(10) PRIMARY KEY,
MEMBER_ID VARCHAR2(30), -- FK : MEMBER-EMAIL
TRACK_NUM NUMBER(10), -- FK : TRACK-TRACK_NUM
COMMENTS_CONTENT VARCHAR2(300),
COMMENTS_WRITE_DATE DATE
);

DROP SEQUENCE COMMENTS_SEQ;
CREATE SEQUENCE COMMENTS_SEQ;