DROP TABLE FOLLOW;
CREATE TABLE FOLLOW
(
FOLLOW_NUM NUMBER(10) PRIMARY KEY,
FOLLOWER VARCHAR2(30), --FK : MEMBER-EMAIL
ARTIST VARCHAR2(30) --FK : MEMBER-EMAIL
);

DROP SEQUENCE FOLLOW_SEQ;
CREATE SEQUENCE FOLLOW_SEQ;