DROP TABLE MAIN_AD;
CREATE TABLE MAIN_AD(
	AD_IMG_NUM NUMBER(10) PRIMARY KEY,
	AD_FILE_NUM NUMBER(10),--FK
	URL VARCHAR2(1000),--클릭 시 이동할 주소
	DESCRIPTION VARCHAR2(120)--간단한 설명
);

DROP SEQUENCE MAIN_AD_SEQ;
CREATE SEQUENCE MAIN_AD_SEQ;