DROP TABLE MAIN_AD_FILE;
CREATE TABLE MAIN_AD_FILE(
	AD_FILE_NUM NUMBER(10) PRIMARY KEY,
	AD_ORG_FILE_NAME VARCHAR2(1000),
	AD_SAVED_FILE_NAME VARCHAR2(1000),
	AD_FILE_SIZE NUMBER(10)
);

DROP SEQUENCE MAIN_AD_FILE_SEQ;
CREATE SEQUENCE MAIN_AD_FILE_SEQ;