DROP TABLE MEMBER;
CREATE TABLE MEMBER(
	MEMBER_ID VARCHAR2(90) PRIMARY KEY,
	MEMBER_PWD VARCHAR2(30),
	MEMBER_INTRODUCE VARCHAR2(90),
	MEMBER_NICKNAME VARCHAR2(30),
	MEMBER_URL VARCHAR2(50),   --UNIQUE
	MEMBER_IMG_NUM NUMBER(10), --이미지테이블을 참조하는 FK
	MEMBER_HIMG_NUM NUMBER(10), --헤더이미지테이블을 참조하는 FK
	MEMBER_CONDITION NUMBER(2),  --계정상태를 저장하는 속성
	MEMBER_JOIN_DATE DATE	
);

DROP SEQUENCE MEMBER_SEQ;
CREATE SEQUENCE MEMBER_SEQ;