DROP MEMBER_IMG;
CREATE MEMBER_IMG
(
MEMBER_IMG_NUM NUMBER(10) PRIMARY KEY,
ORG_FILE_NAME VARCHAR2(600),
SAVED_FILE_NAME VARCHAR2(600),
FILE_SIZE NUMBER(10)
);

DROP SEQUENCE MEMBER_IMG_SEQ;
CREATE SEQUENCE MEMBER_IMG_SEQ;
