DROP TABLE MEMBER_HIMG;
CREATE TABLE MEMBER_HIMG
(
MEMBER_HIMG_NUM NUMBER(10) PRIMARY KEY,
ORG_FILE_NAME VARCHAR2(600),
SAVED_FILE_NAME VARCHAR2(600),
FILE_SIZE NUMBER(10)
);

DROP SEQUENCE MEMBER_HIMG_SEQ;
CREATE SEQUENCE MEMBER_HIMG_SEQ;