DROP TABLE MESSAGE;
CREATE TABLE MESSAGE
(
MESSAGE_NUM NUMBER(10) PRIMARY KEY,
SEND_MEM VARCHAR2(30), --FK : MEMBER-EMAIL
RECEIVE_MEM VARCHAR2(30), --FK : MEMBER-EMAIL
CONTENT VARCHAR2(150),
SEND_DATE DATE
);

DROP SEQUENCE MESSAGE_SEQ;
CREATE SEQUENCE MESSAGE_SEQ;