DROP TABLE PLAYLIST_LIKE;
CREATE TABLE PLAYLIST_LIKE
(
PLAYLIST_LIKE_NUM NUMBER(10) PRIMARY KEY,
MEMBER_ID VARCHAR2(30),  --MEMBER테이블을 위한FK
PLAYLIST_INFO_NUM NUMBER(10) -- FK : PLAYLIST_INFO를 위한FK
);

DROP SEQUENCE PLAYLIST_LIKE_SEQ;
CREATE SEQUENCE PLAYLIST_LIKE_SEQ;