DROP TABLE PLAYLIST_IMG;
CREATE TABLE PLAYLIST_IMG
(
PLAYLIST_IMG_NUM NUMBER(10) PRIMARY KEY,
ORG_FILE_NAME VARCHAR2(600),
SAVED_FILE_NAME VARCHAR2(600),
FILE_SIZE NUMBER(10)
);

DROP SEQUENCE PLAYLIST_IMG_SEQ;
CREATE SEQUENCE PLAYLIST_IMG_SEQ;