DROP TABLE PLAYLIST_INFO;
CREATE TABLE PLAYLIST_INFO(
	PLAYLIST_INFO_NUM NUMBER(10) PRIMARY KEY,
	MEMBER_ID VARCHAR2(30),  --MEMBER테이블을 참조하는 FK
	PLAYLIST_TITLE VARCHAR2(60),
	PLAYLIST_COMMENT VARCHAR2(600),
	PLAYLIST_PUBLIC NUMBER(1),
	PLAYLIST_LIKECOUNT NUMBER(10),
	PLAYLIST_IMG_NUM NUMBER(10),  --PLAYLIST_IMG테이블을 위한 FK
	PLAYLIST_RELEASE_DATE DATE
);

DROP SEQUENCE PLAYLIST_INFO_SEQ;
CREATE SEQUENCE PLAYLIST_INFO_SEQ;