DROP TABLE PLAYLIST;
CREATE TABLE PLAYLIST(
	PLAYLIST_NUM NUMBER(10) PRIMARY KEY,
	TRACK_NUM NUMBER(10), --TRACK테이블을 위한 FK
	PLAYLIST_INFO_NUM NUMBER(10) --PLAYLIST_INFO테이블을 위한 FK
);

DROP SEQUENCE PLAYLIST_SEQ;
CREATE SEQUENCE PLAYLIST_SEQ;
