DROP TABLE PLAYLIST_TAG;
CREATE TABLE PLAYLIST_TAG
(
PLAYLIST_TAG_NUM NUMBER(10) PRIMARY KEY,
PLAYLIST_TAG_NAME VARCHAR2(50),
PLAYLIST_INFO_NUM NUMBER(10)    --FK FOR ALBUM_INFO
);

DROP SEQUENCE PLAYLIST_TAG_SEQ;
CREATE SEQUENCE PLAYLIST_TAG_SEQ;