DROP TABLE REPORT;
CREATE TABLE REPORT(
	REPORT_NUM NUMBER(10) PRIMARY KEY,
	REPORTER_ID VARCHAR2(30),  --멤버테이블을 위한 FK
	REPORT_ACCEPT NUMBER(1),
	REPORT_TYPE_NUM NUMBER(10),  --REPORT_TYPE을 위한 FK
	REPORT_CONTENT VARCHAR2(900),
	REPORT_TRACK_NUM NUMBER(10),  --TRACK_TABLE을 위한 FK
);

DROP SEQUENCE REPORT_SEQ;
CREATE SEQUENCE REPORT_SEQ;
