DROP TABLE TRACK;
CREATE TABLE TRACK(
	TRACK_NUM NUMBER(10) PRIMARY KEY,
	TRACK_TITLE VARCHAR2(60),
	TRACK_UPLOADER VARCHAR2(30),           -- �������̺��� ����Ű�� Ű��
	TRACK_ARTIST VARCHAR2(60),              -- ���� �۰��(EX �ۼ����� �г���)
	TRACK_PUBLIC NUMBER(1),
	TRACK_COMMENT VARCHAR2(90),
	TRACK_FILE_NUM NUMBER(10),        --������ ���̺��� ���� FK
	TRACK_IMG_NUM NUMBER(10),         --Ʈ���̹��� ���̺��� ���� FK
	TRACK_RELEASE_DATE DATE,
	TRACK_REPORT_COUNT NUMBER(10),          --�Ű����� Ƚ�� ����
	TRACK_CONDITION NUMBER(2),        --�Ű������� ó��
	TRACK_PLAYCOUNT NUMBER(20),            --����Ƚ��
	TRACK_LIKECOUNT NUMBER(20),
  TRACK_COMTCOUNT NUMBER(20), --댓글 누적횟수
	GENRE_CODE NUMBER(10)             --�帣���̺��� ���� FK
);
DROP SEQUENCE TRACK_SEQ;
CREATE SEQUENCE TRACK_SEQ;
