DROP TABLE TRACK_TAG;
CREATE TABLE TRACK_TAG
(
TRACK_TAG_NUM NUMBER(10) PRIMARY KEY,
TRACK_TAG_NAME VARCHAR2(50),
TRACK_NUM NUMBER(10)   --TRACK���̺� FK
);
DROP SEQUENCE TRACK_TAG_SEQ;
CREATE SEQUENCE TRACK_TAG_SEQ;
