DROP TABLE TRACK_LIKE;
CREATE TABLE TRACK_LIKE
(
TRACK_LIKE_NUM NUMBER(10) PRIMARY KEY,
MEMBER_ID VARCHAR2(30),  --MEMBER���̺��� ����FK
TRACK_NUM NUMBER(10) -- FK : PLAYLIST_INFO�� ����FK
);
DROP SEQUENCE TRACK_LIKE_SEQ;
CREATE SEQUENCE TRACK_LIKE_SEQ;
